[package]
name = "scuderia-term"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
iced = "0.10.0"
serde = { version = "1.0.189", features = ["derive"] }
toml = "0.8.2"
